In [160]:
import pandas as pd
import numpy as np

In [161]:
df = pd.read_csv('C:\\data_vis\\data\\raw\\goodreads_dataset_copy.csv')

C:\Users\79378\AppData\Local\Temp\ipykernel_18704\2040014183.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:\\data_vis\\data\\raw\\goodreads_dataset_copy.csv')

In [162]:
df.head()

,book_id,title,author,rating,ratings_count,reviews_count,description,genres,pages,format,publication_date,literary_awards,original_title,series,setting,characters,isbn,language
0,1,Harry Potter and the Half-Blood Prince,J.K. Rowling,4.58,3674555,70957,"It is the middle of the summer, but there is a...","Fantasy, Fiction, Young Adult, Harry Potter, M...",652.0,Paperback,"September 16, 2006","Locus Award, Audie Award, The Quill Award",Harry Potter and the Half-Blood Prince,Harry Potter,"Hogwarts School of Witchcraft and Wizardry, En...","Ron Weasley, Petunia Dursley, Vernon Dursley, ...",NaN,English
1,2,Harry Potter and the Order of the Phoenix,J.K. Rowling,4.50,3814489,78489,Harry Potter is about to start his fifth year ...,"Fantasy, Fiction, Young Adult, Harry Potter, M...",870.0,Paperback,"September 01, 2004","Bram Stoker Award, Anthony Award, Mythopoeic F...",Harry Potter and the Order of the Phoenix,Harry Potter,"Hogwarts School of Witchcraft and Wizardry, Lo...","Sirius Black, Ron Weasley, Petunia Dursley, Ve...",9780439686525,English
2,3,Harry Potter and the Sorcerer's Stone,J.K. Rowling,4.47,11475756,195559,Harry Potter &amp; the Sorcerers Stone Rowling...,"Fantasy, Fiction, Young Adult, Harry Potter, M...",309.0,Hardcover,"November 01, 2003","Mythopoeic Fantasy Award, British Book Award, ...",Harry Potter and the Philosopher’s Stone,Harry Potter,"London, England, Hogwarts School of Witchcraft...","Ron Weasley, Petunia Dursley, Vernon Dursley, ...",9780439554930,English
3,4,Harry Potter and the Chamber of Secrets,J.K. Rowling,4.43,4521488,98328,The Dursleys were so mean and hideous that sum...,"Fantasy, Fiction, Young Adult, Harry Potter, M...",352.0,Hardcover,"November 01, 2003","Mythopoeic Fantasy Award, British Book Award, ...",Harry Potter and the Chamber of Secrets,Harry Potter,Hogwarts School of Witchcraft and Wizardry,"Ron Weasley, Petunia Dursley, Vernon Dursley, ...",9780439554893,English
4,5,Harry Potter and the Prisoner of Azkaban,J.K. Rowling,4.58,4874031,103710,"Harry Potter, along with his best friends, Ron...","Fantasy, Fiction, Young Adult, Harry Potter, M...",547.0,Mass Market Paperback,"May 01, 2004","Bram Stoker Award, Hugo Award, Locus Award, Wh...",Harry Potter and the Prisoner of Azkaban,Harry Potter,"Hogwarts School of Witchcraft and Wizardry, Sc...","Sirius Black, Ron Weasley, Petunia Dursley, Ve...",9780439655484,English

In [163]:
df.isna().sum()

book_id                  0
title                    0
author                   0
rating                   0
ratings_count            0
reviews_count            0
description           4563
genres               32366
pages                 3979
format                 348
publication_date       354
literary_awards     101425
original_title        6915
series               89884
setting              97770
characters           95156
isbn                  2051
language              1230
dtype: int64

In [ ]:
df['literary_awards'] = df['literary_awards'].fillna('None') #if there is no awards, fill with 'None'

In [166]:
df.describe()

,book_id,rating,ratings_count,reviews_count,pages
count,114658.000000,114658.000000,1.146580e+05,114658.000000,110679.000000
mean,59916.459218,3.572817,4.737562e+04,1623.387893,282.716351
std,34502.431547,1.162257,3.539430e+05,9244.260666,1192.365549
min,1.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,31292.250000,3.590000,9.000000e+00,1.000000,144.000000
50%,58692.500000,3.900000,1.380000e+02,13.000000,242.000000
75%,89663.750000,4.130000,2.711000e+03,174.000000,355.000000
max,120890.000000,5.000000,1.147972e+07,195674.000000,380720.000000

In [ ]:
df['pages'] = df['pages'].fillna(df['pages'].median()) #fill the value in 'pages' with median

In [ ]:
df['language'] = df['language'].fillna('English') #if there are noo language value, put English

In [ ]:
df['format'] = df['format'].fillna(df['format'].mode()[0]) #fill format with mode value (the most popular)

In [ ]:
df['original_title'] = df['original_title'].fillna(df['title'])#if there are no title, fill with 'title'

In [ ]:
df['publication_date'] = df['publication_date'].fillna("Unknown") #if there are no publication date fill with 'Unknown'

In [ ]:
df['isbn'] = df['isbn'].fillna("Unknown") #if there are no isbn fill with 'Unknown'

In [ ]:
df['description'] = df['description'].fillna("") #put " " instead of empty description

In [ ]:
#replace Null values of ['series']
def clean_series(row):
    title = str(row['title'])
    current_series = str(row['series'])
    
    #try to retrieve the name of series from title
    if pd.notna(row['series']) and str(row['series']).strip() != '':
        return str(row['series']).strip()
    elif ':' in title:
        return title.split(':')[0].strip()
    elif '-' in title:
        return title.split('-')[0].strip()


df['series'] = df.apply(clean_series, axis=1)

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114658 entries, 0 to 114657
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   book_id           114658 non-null  int64
 1   title             114658 non-null  object
 2   author            114658 non-null  object
 3   rating            114658 non-null  float64
 4   ratings_count     114658 non-null  int64
 5   reviews_count     114658 non-null  int64
 6   description       114658 non-null  object
 7   genres            82292 non-null   object
 8   pages             114658 non-null  float64
 9   format            114658 non-null  object
 10  publication_date  114658 non-null  object
 11  literary_awards   114658 non-null  object
 12  original_title    114658 non-null  object
 13  series            66126 non-null   object
 14  setting           16888 non-null   object
 15  characters        19502 non-null   object
 16  isbn              114658 non-null  object
 17  language          114658 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 15.7+ MB